In [4]:
META_FILENAME = "images/metadata/images.csv"
IMAGES_DIR = "images/small"

In [5]:
import pandas as pd

def load_metadata():
    metadata = pd.read_csv(META_FILENAME)
    return metadata

meta = load_metadata()
meta.head()

      image_id  height  width             path
0  010-mllS7JL     106    106  14/14fe8812.jpg
1  01dkn0Gyx0L     122    122  da/daab0cad.jpg
2  01sUPg0387L     111    111  d2/d2daaae9.jpg
3  1168jc-5r1L     186    186  3a/3a4e88e6.jpg
4  11RUV5Fs65L      30    500  d9/d91ab9cf.jpg

In [ ]:
# find small images
def find_small_images(df):
    df = df[(df['width'] < 1000) | (df['height'] < 1000)]
    return df

smol = find_small_images(meta)
print(f"Small images to be removed ({len(smol)} of {len(meta)}):")
smol.head()

Small images to be removed (55334 of 398212):

      image_id  height  width             path
0  010-mllS7JL     106    106  14/14fe8812.jpg
1  01dkn0Gyx0L     122    122  da/daab0cad.jpg
2  01sUPg0387L     111    111  d2/d2daaae9.jpg
3  1168jc-5r1L     186    186  3a/3a4e88e6.jpg
4  11RUV5Fs65L      30    500  d9/d91ab9cf.jpg

In [13]:
import os
def remove_images(df: pd.DataFrame, images_dir:str, dry_run:bool=False) -> int:
    total_removed = 0
    for _, row in df.iterrows():
        image_path = f"{images_dir}/{row['path']}"
        try:
            if not dry_run:
                os.remove(image_path)
            total_removed += 1
        except FileNotFoundError:
            pass
    return total_removed
        
tot = remove_images(smol, IMAGES_DIR, dry_run=False)
print(f"Total images removed: {tot}")

Total images removed: 55334